Spring boot practice add order
BolsunovaNataliia/book-shop pull request #13
Opened 2024-01-03 23:00 UTC by BolsunovaNataliia

2024-01-04 08:48 UTC, TarasYurkovskyi approved these changes
GJ

2024-01-04 08:48 UTC, TarasYurkovskyi commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +        return orderMapper.toDto(savedOrder);
i think we can split this method)

2024-01-04 09:22 UTC, BolsunovaNataliia commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +        return orderMapper.toDto(savedOrder);
Agree with you.

2024-01-04 09:47 UTC, d1sam requested changes
good job, but there are some change should be done!

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/OrderController.java
Available for users with role ADMIN

- POST: /api/books/
- PUT: /api/books/{id}
- DELETE: /api/books/{id}
- POST: /api/categories
- PUT: /api/categories/{id}
- DELETE: /api/categories/{id}
- PATCH: /api/orders/{id}

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/OrderController.java
> +    @PutMapping("/{id}")
```suggestion
    @PatchMapping("/{id}")
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/OrderController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/OrderController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/OrderController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/OrderController.java
> +    @PreAuthorize("hasAnyAuthority('ROLE_USER', 'ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyAuthority('ROLE_USER')")
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/Order.java
> +@RequiredArgsConstructor
```suggestion
@RequiredArgsConstructor
@NoArgsConstructor
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/OrderItem.java
> +@RequiredArgsConstructor
```suggestion
@RequiredArgsConstructor
@NoArgsConstructor
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +        BigDecimal total = new BigDecimal(0);
```suggestion
        BigDecimal total = BigDecimal.ZERO;
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +        return orderItemDtos;
use for this purpose mapper

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/mapper/OrderItemMapper.java
> +    OrderItemDto toDto(OrderItem orderItem);
```suggestion
    OrderItemDto toDto(OrderItem orderItem);
    
    @IterableMapping(qualifiedByName = "toDto")
    List<OrderItemDto> toDtoList(List<OrderItem> orderItems);
```

2024-01-04 09:47 UTC, d1sam commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +                        "There is not found order with id " + orderId));
```suggestion
        OrderItem orderItem = orderItemRepository.findByIdAndOrderId(itemId, orderId)
      .orElseThrow(() -> new EntityNotFoundException("OrderItem with id " + itemId + " not found in order with id "
        + orderId));

2024-01-04 13:51 UTC, BolsunovaNataliia commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +                        "There is not found order with id " + orderId));
I couldn't check user in such case...

2024-01-04 15:10 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/model/Order.java
> +    @ManyToOne
Try to avoid EAGER relations.

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/model/OrderItem.java
> +    @ManyToOne
Try to avoid EAGER relations.

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/model/OrderItem.java
> +    @ManyToOne
Try to avoid EAGER relations.

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/repository/order/OrderRepository.java
> +    Optional<Order> findAllByUserId(@PathVariable(name = "id") Long userId);
```suggestion
    Optional<Order> findAllByUserId(Long userId);
```

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/repository/orderitem/OrderItemRepository.java
> +    Optional<OrderItem> findByIdAndOrderId(Long userId, Long itemId, Long orderId);
```suggestion
    Optional<OrderItem> findByIdAndOrderIdForCurrentUser(Long userId, Long itemId, Long orderId);
```

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +    public OrderDto placeOrder(Long userId, PlaceOrderRequestDto requestDto) {
Can you simplify this method? (By extracting some logical parts into separate private methods for example)

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +    public OrderDto updateStatusOrder(Long orderId,
```suggestion
    public OrderDto updateOrderStatus(Long orderId,
```

2024-01-04 15:10 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/service/OrderServiceImpl.java
> +    public Set<OrderItemDto> getAllOrderItems(Long userId, Long orderId, Pageable pageable) {
Improve this method the same way you did in `getItemById`. (Create similar custom repository method but without specification of `orderItemId`)

2024-01-05 09:32 UTC, d1sam approved these changes
well done!

2024-01-05 09:41 UTC, merged