Spring boot testing book
BolsunovaNataliia/book-shop pull request #15
Opened 2024-01-10 08:48 UTC by BolsunovaNataliia

2024-01-11 06:21 UTC, ponomvrenko approved these changes
LGTM

2024-01-11 11:05 UTC, yevheniisynytsia requested changes
Well done! Some comments to improve tests left

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/controller/BookController.java
>      public List<BookDto> findAll(Authentication authentication, Pageable pageable) {
```suggestion
    public List<BookDto> findAll(Pageable pageable) {
```

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/ApplicationTests.java
> +class ApplicationTests {
you could leave the name as it was. Not much sense to rename it

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/controller/BookControllerTest.java
> +                result.getResponse().getContentAsString(), BookDto[].class);
It is better to test objects instead of testing their presence in your response

+ you can map it to list, not an array
then you can assertEquals(expectedObjectsList, actual)

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/controller/BookControllerTest.java
> +    @AfterAll
this is usually placed in the beginning so that you have "configurations" - tests

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/repository/book/BookRepositoryTest.java
> +        assertTrue(actualTitles.containsAll(expectedTitles));
it is easier to just compare lists

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/service/BookServiceImplTest.java
> +    private BookServiceImpl bookService;
place this after your mocks

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/repository/book/BookRepositoryTest.java
> +    @Test
do not forget about display name

2024-01-11 11:05 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookshop/service/BookServiceImplTest.java
> +        assertEquals(expected.get(0).getTitle(), actual.get(0).getTitle());
I would say it is better to check if actual is not null and compare expected list with actual

2024-01-11 11:07 UTC, yevheniisynytsia commented on pom.xml
> +        </dependency>
do you use test containers?

2024-01-15 06:17 UTC, BolsunovaNataliia commented on src/test/java/mate/academy/bookshop/ApplicationTests.java
> +class ApplicationTests {
I'm sure the name should match the name in the main package.

2024-01-15 10:18 UTC, d1sam approved these changes
well done!

2024-01-17 22:07 UTC, merged