added controller, dto, mapper, exception and config packages
BolsunovaNataliia/book-shop pull request #2
Opened 2023-12-07 00:23 UTC by BolsunovaNataliia

2023-12-07 10:51 UTC, forzen123212 approved these changes
good job, just some style fixes!

2023-12-07 10:51 UTC, forzen123212 commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +        return bookService.findById(id);
Краще переіменувати findBookById на getById 
find ми використовуєм коли повертаємо Optional<BookDto> 
get коли точне значення яке не може бути null

2023-12-07 10:51 UTC, forzen123212 commented on src/main/java/mate/academy/bookshop/service/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
implement isbm initialization into mapper

2023-12-07 10:51 UTC, forzen123212 commented on src/main/resources/application.properties
> +spring.datasource.password=fiasko13@3
remove your pass

2023-12-07 10:51 UTC, forzen123212 commented on src/main/resources/application.properties
> +
remove empty line

2023-12-07 15:17 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2023-12-07 15:17 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +        return bookService.findById(id);
It's a good suggestion, but not required.

2023-12-07 15:17 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/service/BookServiceImpl.java
> +        book.setIsbn("" + new Random().nextInt(1000));
Why is it generated? I'm not sure that stores generate ISBN of some book they want to sell. So, make it an API parameter.

2023-12-07 15:17 UTC, vovasalyha commented on src/main/resources/application.properties
> +spring.datasource.password=fiasko13@3
Yep, better use some dummy passwords.

2023-12-07 19:02 UTC, BolsunovaNataliia commented on src/main/java/mate/academy/bookshop/service/BookServiceImpl.java
> +        book.setIsbn("" + new Random().nextInt(1000));
:) A little drifted.

2023-12-11 09:35 UTC, d1sam approved these changes
Well done!

2023-12-11 09:37 UTC, merged