Spring boot data jpa solution
BolsunovaNataliia/book-shop pull request #3
Opened 2023-12-11 13:09 UTC by BolsunovaNataliia

2023-12-12 09:48 UTC, BohdanTrue reviewed
Good job! But you forgot to do one method (update)
![image](https://github.com/BolsunovaNataliia/book-shop/assets/94116191/7d65e132-f9f3-496f-9c49-03fbc5235bc2)

2023-12-12 09:48 UTC, BohdanTrue commented on src/main/java/mate/academy/bookshop/model/Book.java
>      }
redudant, lombok already create all constructors for you

2023-12-12 09:49 UTC, BohdanTrue requested changes
Good job! But you forgot to do one method (update)
![image](https://github.com/BolsunovaNataliia/book-shop/assets/94116191/7d65e132-f9f3-496f-9c49-03fbc5235bc2)

2023-12-12 09:57 UTC, d1sam requested changes
good job, but please look at my comments and add necessary put method to your api :)

2023-12-12 09:57 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/BookController.java
Book Endpoints:
- PUT: /api/books/{id} (Update a specific book)

2023-12-12 09:57 UTC, d1sam commented on src/main/resources/application.properties
>  spring.jackson.deserialization.fail-on-unknown-properties=true
```suggestion
spring.jackson.deserialization.fail-on-unknown-properties=true
server.servlet.context-path=/api
```

2023-12-13 15:31 UTC, vovasalyha approved these changes
LGTM

2023-12-13 15:31 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +    @PutMapping(value = "/{id}", consumes = {"application/json"})
Specifying `consumes` attribute is not necessary here as it is the default value when you receive some class as a body.

2023-12-13 17:09 UTC, merged