Security related functionality part two
BolsunovaNataliia/book-shop pull request #9
Opened 2023-12-26 13:37 UTC by BolsunovaNataliia

2023-12-26 15:06 UTC, DPotapov93 commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +        return bookService.findAll(user.getEmail(), pageable);
"I'm not sure, but it seems that it's not required in our task. We just need access to all books in the store to choose them from the list."

2023-12-26 15:06 UTC, DPotapov93 approved these changes
Good Job!

2023-12-27 08:26 UTC, d1sam requested changes
Good job, but please make changes according to my comments and remove changes from another hw.

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/Application.java
Why did you rename this class?

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/AuthController.java
> +    }
it's not for this hw.

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/dto/UserLoginRequestDto.java
login is not for this hw.

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +    private Set<Role> roles = new HashSet<>();
please exclude from `equals&hashcode`

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/repository/user/UserRepository.java
> +    @Query("SELECT u FROM User u LEFT JOIN FETCH u.roles WHERE u.email = :email")
```suggestion
```
you can use named query

2023-12-27 08:26 UTC, d1sam commented on src/main/resources/application.properties
> +spring.datasource.password=fiasko13@3
```suggestion
spring.datasource.password=*****************
```

2023-12-27 08:26 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-insert-books.yaml
> +              - column: { name: cover_image, value: "some link 3" }
```suggestion
              - column: { name: cover_image, value: "some link 3" }
              
```

2023-12-27 08:26 UTC, d1sam commented on src/main/java/mate/academy/bookshop/security/CustomUserDetailsService.java
it's not for this hw.

2023-12-27 12:58 UTC, BolsunovaNataliia commented on src/main/java/mate/academy/bookshop/Application.java
To unify.

2023-12-27 13:29 UTC, d1sam approved these changes
Well done!

2023-12-27 13:31 UTC, merged